[package]
name = "ml-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace crates
common = { path = "../common" }
weaver = { path = "../weaver" }

# PyO3 for Python bindings
pyo3 = { version = "0.20", features = ["auto-initialize"] }

# Async
tokio = { workspace = true }
async-trait = "0.1"

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Logging
log = "0.4"

[dev-dependencies]
tempfile = "3.8"
