[package]
name = "indexing"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
sled = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }

# HNSW vector index (pure Rust!)
hnsw_rs = "0.3"

[dev-dependencies]
tempfile = "3.8"
