[package]
name = "tabagent-model-cache-bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "tabagent_model_cache_py"
crate-type = ["cdylib"]

[dependencies]
tabagent-model-cache = { path = "../model-cache" }
pyo3 = { workspace = true, features = ["extension-module", "abi3-py39"] }
tokio = { version = "1.35", features = ["full"] }
serde_json = { workspace = true }

[build-dependencies]
pyo3-build-config = "0.21"

